cmake_minimum_required(VERSION 3.17)
project(BitwiseOperation)

set(CMAKE_CXX_STANDARD 17)
include_directories(util)
add_executable(BitwiseOperation main.cpp util/util.h test_factory.h L29_divide/L29_divide.cpp L29_divide/L29_divide.h L67_addBinary/L67_addBinary.cpp L67_addBinary/L67_addBinary.h L78_subsets/L78_subsets.cpp L78_subsets/L78_subsets.h L89_grayCode/L89_grayCode.cpp L89_grayCode/L89_grayCode.h L90_subsetsWithDup/L90_subsetsWithDup.cpp L90_subsetsWithDup/L90_subsetsWithDup.h L136_singleNumber/L136_singleNumber.cpp L136_singleNumber/L136_singleNumber.h L137_singleNumber/L137_singleNumber.cpp L137_singleNumber/L137_singleNumber.h L187_findRepeatedDnaSequences/L187_findRepeatedDnaSequences.cpp L187_findRepeatedDnaSequences/L187_findRepeatedDnaSequences.h)